//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRBD_2S_Aurélie.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRBD_2S_Aurélie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string Connexion_Annuler {
            get {
                return ResourceManager.GetString("Connexion_Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si vous n&apos;êtes pas encore inscrit, veuillez cliquer.
        /// </summary>
        public static string Connexion_Message_1 {
            get {
                return ResourceManager.GetString("Connexion_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ici.
        /// </summary>
        public static string Connexion_Message_2 {
            get {
                return ResourceManager.GetString("Connexion_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pour vous enregistrer!.
        /// </summary>
        public static string Connexion_Message_3 {
            get {
                return ResourceManager.GetString("Connexion_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string Connexion_Password {
            get {
                return ResourceManager.GetString("Connexion_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string Connexion_SingIn {
            get {
                return ResourceManager.GetString("Connexion_SingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string Connexion_Title {
            get {
                return ResourceManager.GetString("Connexion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username:.
        /// </summary>
        public static string Connexion_UserName {
            get {
                return ResourceManager.GetString("Connexion_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe doit contenir au moins un chiffre, une lettre majuscule et un caractère non alphanumérique..
        /// </summary>
        public static string Error_BadFormat {
            get {
                return ResourceManager.GetString("Error_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce mot de passe est érroné.
        /// </summary>
        public static string Error_BadPassword {
            get {
                return ResourceManager.GetString("Error_BadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de l&apos;email est érroné.
        /// </summary>
        public static string Error_Email {
            get {
                return ResourceManager.GetString("Error_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet utilisateur existe déjà! Veuillez vous connecter..
        /// </summary>
        public static string Error_Exist {
            get {
                return ResourceManager.GetString("Error_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet Email existe déjà. Veuillez vous connecter .
        /// </summary>
        public static string Error_ExistEmail {
            get {
                return ResourceManager.GetString("Error_ExistEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce champ doit avoir au minimun 3 caractères.
        /// </summary>
        public static string Error_MinLength {
            get {
                return ResourceManager.GetString("Error_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe doit contenir au moins 8 caractères.
        /// </summary>
        public static string Error_MinLengthPassword {
            get {
                return ResourceManager.GetString("Error_MinLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre de tags associé au post doit être inférieur ou égal à 3.
        /// </summary>
        public static string Error_NbTags {
            get {
                return ResourceManager.GetString("Error_NbTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet utilisateur n&apos;existe pas.
        /// </summary>
        public static string Error_NotExist {
            get {
                return ResourceManager.GetString("Error_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les deux mots de passe doivent être identiques.
        /// </summary>
        public static string Error_PasswordConfirm {
            get {
                return ResourceManager.GetString("Error_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce champ est requis.
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email:.
        /// </summary>
        public static string Signup_Email {
            get {
                return ResourceManager.GetString("Signup_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string Signup_FullName {
            get {
                return ResourceManager.GetString("Signup_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si vous êtes déjà inscrit, veuillez cliquer .
        /// </summary>
        public static string Signup_Message1 {
            get {
                return ResourceManager.GetString("Signup_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ici.
        /// </summary>
        public static string Signup_Message2 {
            get {
                return ResourceManager.GetString("Signup_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pour vous connecter.
        /// </summary>
        public static string Signup_Message3 {
            get {
                return ResourceManager.GetString("Signup_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string Signup_Password {
            get {
                return ResourceManager.GetString("Signup_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription.
        /// </summary>
        public static string Signup_Title {
            get {
                return ResourceManager.GetString("Signup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur.
        /// </summary>
        public static string Signup_UserName {
            get {
                return ResourceManager.GetString("Signup_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez votre mot de passe.
        /// </summary>
        public static string SignupPassword_Confirm {
            get {
                return ResourceManager.GetString("SignupPassword_Confirm", resourceCulture);
            }
        }
    }
}
