//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRBD_2S_Aurélie.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRBD_2S_Aurélie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accepter.
        /// </summary>
        public static string btn_Accept {
            get {
                return ResourceManager.GetString("btn_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un Tag.
        /// </summary>
        public static string btn_AddTag {
            get {
                return ResourceManager.GetString("btn_AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string btn_annuler {
            get {
                return ResourceManager.GetString("btn_annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string btn_Delete {
            get {
                return ResourceManager.GetString("btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un Tag.
        /// </summary>
        public static string btn_DeleteTag {
            get {
                return ResourceManager.GetString("btn_DeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string btn_Modifier {
            get {
                return ResourceManager.GetString("btn_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un Tag.
        /// </summary>
        public static string btn_UpdateTag {
            get {
                return ResourceManager.GetString("btn_UpdateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string btn_valider {
            get {
                return ResourceManager.GetString("btn_valider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string Connexion_Annuler {
            get {
                return ResourceManager.GetString("Connexion_Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si vous n&apos;êtes pas encore inscrit, veuillez cliquer.
        /// </summary>
        public static string Connexion_Message_1 {
            get {
                return ResourceManager.GetString("Connexion_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ici.
        /// </summary>
        public static string Connexion_Message_2 {
            get {
                return ResourceManager.GetString("Connexion_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pour vous enregistrer!.
        /// </summary>
        public static string Connexion_Message_3 {
            get {
                return ResourceManager.GetString("Connexion_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe :.
        /// </summary>
        public static string Connexion_Password {
            get {
                return ResourceManager.GetString("Connexion_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string Connexion_SingIn {
            get {
                return ResourceManager.GetString("Connexion_SingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string Connexion_Title {
            get {
                return ResourceManager.GetString("Connexion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pseudonyme : .
        /// </summary>
        public static string Connexion_UserName {
            get {
                return ResourceManager.GetString("Connexion_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Êtes-vous de vouloir supprimer post?.
        /// </summary>
        public static string Delete_Message1 {
            get {
                return ResourceManager.GetString("Delete_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette opération est irréversible!.
        /// </summary>
        public static string Delete_Message2 {
            get {
                return ResourceManager.GetString("Delete_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajoutez un commentaire.
        /// </summary>
        public static string DetailPost_AddComment {
            get {
                return ResourceManager.GetString("DetailPost_AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Question posée par.
        /// </summary>
        public static string DetailPost_AskedBy {
            get {
                return ResourceManager.GetString("DetailPost_AskedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler la réponse acceptée.
        /// </summary>
        public static string DetailPost_CancelAcceptAnswer {
            get {
                return ResourceManager.GetString("DetailPost_CancelAcceptAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaire(s).
        /// </summary>
        public static string DetailPost_Commentaire {
            get {
                return ResourceManager.GetString("DetailPost_Commentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réponse(s).
        /// </summary>
        public static string DetailPost_nbAnswers {
            get {
                return ResourceManager.GetString("DetailPost_nbAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publiez votre reponse.
        /// </summary>
        public static string DetailPost_Reply {
            get {
                return ResourceManager.GetString("DetailPost_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Score :.
        /// </summary>
        public static string DetailPost_Score {
            get {
                return ResourceManager.GetString("DetailPost_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre reponse.
        /// </summary>
        public static string DetailPost_YourAnswer {
            get {
                return ResourceManager.GetString("DetailPost_YourAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -1.
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe doit contenir au moins un chiffre, une lettre majuscule et un caractère non alphanumérique..
        /// </summary>
        public static string Error_BadFormat {
            get {
                return ResourceManager.GetString("Error_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce mot de passe est érroné.
        /// </summary>
        public static string Error_BadPassword {
            get {
                return ResourceManager.GetString("Error_BadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de l&apos;email est érroné.
        /// </summary>
        public static string Error_Email {
            get {
                return ResourceManager.GetString("Error_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet utilisateur existe déjà! Veuillez vous connecter..
        /// </summary>
        public static string Error_Exist {
            get {
                return ResourceManager.GetString("Error_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet Email existe déjà. Veuillez vous connecter .
        /// </summary>
        public static string Error_ExistEmail {
            get {
                return ResourceManager.GetString("Error_ExistEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce champ doit avoir au minimun 3 caractères.
        /// </summary>
        public static string Error_MinLength {
            get {
                return ResourceManager.GetString("Error_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe doit contenir au moins 8 caractères.
        /// </summary>
        public static string Error_MinLengthPassword {
            get {
                return ResourceManager.GetString("Error_MinLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre de tags associé au post doit être inférieur ou égal à 3.
        /// </summary>
        public static string Error_NbTags {
            get {
                return ResourceManager.GetString("Error_NbTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet utilisateur n&apos;existe pas.
        /// </summary>
        public static string Error_NotExist {
            get {
                return ResourceManager.GetString("Error_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les deux mots de passe doivent être identiques.
        /// </summary>
        public static string Error_PasswordConfirm {
            get {
                return ResourceManager.GetString("Error_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce champ est requis.
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce tag est déjà associé à ce post.
        /// </summary>
        public static string Error_TagExist {
            get {
                return ResourceManager.GetString("Error_TagExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active.
        /// </summary>
        public static string ListPosts_active {
            get {
                return ResourceManager.GetString("ListPosts_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réponse(s),.
        /// </summary>
        public static string ListPosts_nbAnswers {
            get {
                return ResourceManager.GetString("ListPosts_nbAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Newest.
        /// </summary>
        public static string ListPosts_Newest {
            get {
                return ResourceManager.GetString("ListPosts_Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Poser  une question.
        /// </summary>
        public static string ListPosts_NewQuestion {
            get {
                return ResourceManager.GetString("ListPosts_NewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vote(s)),.
        /// </summary>
        public static string ListPosts_score {
            get {
                return ResourceManager.GetString("ListPosts_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unanswered.
        /// </summary>
        public static string ListPosts_unanswered {
            get {
                return ResourceManager.GetString("ListPosts_unanswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vote.
        /// </summary>
        public static string ListPosts_vote {
            get {
                return ResourceManager.GetString("ListPosts_vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string MainView_connexion {
            get {
                return ResourceManager.GetString("MainView_connexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;s connect.
        /// </summary>
        public static string Mainview_current {
            get {
                return ResourceManager.GetString("Mainview_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déconnexion.
        /// </summary>
        public static string MainView_deconnexion {
            get {
                return ResourceManager.GetString("MainView_deconnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription.
        /// </summary>
        public static string MainView_inscription {
            get {
                return ResourceManager.GetString("MainView_inscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Questions.
        /// </summary>
        public static string MainView_questions {
            get {
                return ResourceManager.GetString("MainView_questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tags.
        /// </summary>
        public static string MainView_tags {
            get {
                return ResourceManager.GetString("MainView_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste de Posts associés au Tag:.
        /// </summary>
        public static string PostsOfTag {
            get {
                return ResourceManager.GetString("PostsOfTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email:.
        /// </summary>
        public static string Signup_Email {
            get {
                return ResourceManager.GetString("Signup_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom: .
        /// </summary>
        public static string Signup_FullName {
            get {
                return ResourceManager.GetString("Signup_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si vous êtes déjà inscrit, veuillez cliquer .
        /// </summary>
        public static string Signup_Message1 {
            get {
                return ResourceManager.GetString("Signup_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ici.
        /// </summary>
        public static string Signup_Message2 {
            get {
                return ResourceManager.GetString("Signup_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pour vous connecter.
        /// </summary>
        public static string Signup_Message3 {
            get {
                return ResourceManager.GetString("Signup_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe:.
        /// </summary>
        public static string Signup_Password {
            get {
                return ResourceManager.GetString("Signup_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription.
        /// </summary>
        public static string Signup_Title {
            get {
                return ResourceManager.GetString("Signup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pseudonyme:.
        /// </summary>
        public static string Signup_UserName {
            get {
                return ResourceManager.GetString("Signup_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez votre mot de passe.
        /// </summary>
        public static string SignupPassword_Confirm {
            get {
                return ResourceManager.GetString("SignupPassword_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du Tag.
        /// </summary>
        public static string Tag_Column1 {
            get {
                return ResourceManager.GetString("Tag_Column1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de posts associés au Tag.
        /// </summary>
        public static string Tag_Column2 {
            get {
                return ResourceManager.GetString("Tag_Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Post(s).
        /// </summary>
        public static string Tag_Posts {
            get {
                return ResourceManager.GetString("Tag_Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +1.
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        public static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
    }
}
